# Generated by Django 5.2.8 on 2025-11-22 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('es_turno_24h', models.BooleanField(default=False, verbose_name='Es turno de 24 horas')),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('minutos_tolerancia', models.IntegerField(default=15)),
                ('tiene_horario_comida', models.BooleanField(default=False)),
                ('hora_inicio_comida', models.TimeField(blank=True, null=True)),
                ('hora_fin_comida', models.TimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Horario',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.tipohorario'),
        ),
    ]
