# Generated by Django 5.2.8 on 2025-11-22 21:28

from django.db import migrations
from datetime import time


def create_default_horarios(apps, schema_editor):
    """Crea los tipos de horario predeterminados"""
    TipoHorario = apps.get_model('attendance', 'TipoHorario')
    
    # Regular con Comida (horario actual por defecto)
    TipoHorario.objects.create(
        nombre="Regular con Comida",
        descripcion="Horario estándar de 9:00 AM a 7:00 PM con salida a comida de 2:00 PM a 4:00 PM",
        es_turno_24h=False,
        hora_entrada=time(9, 0),
        hora_salida=time(19, 0),
        minutos_tolerancia=15,
        tiene_horario_comida=True,
        hora_inicio_comida=time(14, 0),
        hora_fin_comida=time(16, 0),
        activo=True
    )
    
    # Regular sin Comida
    TipoHorario.objects.create(
        nombre="Regular sin Comida",
        descripcion="Horario estándar de 9:00 AM a 7:00 PM sin horario de comida",
        es_turno_24h=False,
        hora_entrada=time(9, 0),
        hora_salida=time(19, 0),
        minutos_tolerancia=15,
        tiene_horario_comida=False,
        activo=True
    )
    
    # Vigilancia 24 horas
    TipoHorario.objects.create(
        nombre="Vigilancia 24h",
        descripcion="Turno de 24 horas con 24 horas de descanso (ciclo de 48 horas)",
        es_turno_24h=True,
        minutos_tolerancia=120,  # 2 horas de tolerancia para turnos largos
        tiene_horario_comida=False,
        activo=True
    )


def reverse_default_horarios(apps, schema_editor):
    """Elimina los tipos de horario predeterminados"""
    TipoHorario = apps.get_model('attendance', 'TipoHorario')
    TipoHorario.objects.filter(
        nombre__in=["Regular con Comida", "Regular sin Comida", "Vigilancia 24h"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_tipohorario_empleado_tipo_horario'),
    ]

    operations = [
        migrations.RunPython(create_default_horarios, reverse_default_horarios),
    ]
