# Generated by Django 5.2.8 on 2025-12-10 22:37

import checador.storage_backends
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_add_default_horarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoVacacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('fecha_inicio_periodo', models.DateField(verbose_name='Inicio del periodo')),
                ('fecha_fin_periodo', models.DateField(verbose_name='Fin del periodo')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Periodo Vacacional',
                'verbose_name_plural': 'Periodos Vacacionales',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='TipoJustificante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('aplica_para', models.CharField(choices=[('RETARDO', 'Retardo'), ('FALTA', 'Falta'), ('AMBOS', 'Ambos')], default='AMBOS', max_length=20, verbose_name='Aplica para')),
                ('requiere_documento', models.BooleanField(default=True, verbose_name='Requiere documento')),
                ('cancela_penalizacion', models.BooleanField(default=True, help_text='Si el justificante aprobado cancela la penalización', verbose_name='Cancela penalización')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Justificante',
                'verbose_name_plural': 'Tipos de Justificantes',
            },
        ),
        migrations.CreateModel(
            name='TipoPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del permiso')),
                ('requiere_aprobacion_gerencia', models.BooleanField(default=False, help_text='Si requiere aprobación adicional de gerencia general', verbose_name='Requiere aprobación de gerencia')),
                ('dias_anticipacion_minimos', models.IntegerField(default=0, help_text='Cuántos días antes debe solicitarse', verbose_name='Días de anticipación mínimos')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Permiso',
                'verbose_name_plural': 'Tipos de Permisos',
            },
        ),
        migrations.AddField(
            model_name='tipohorario',
            name='horas_jornada_completa',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=4, verbose_name='Horas de jornada completa'),
        ),
        migrations.AddField(
            model_name='tipohorario',
            name='requiere_horario_por_dia',
            field=models.BooleanField(default=False, help_text='Activa esto para horarios personalizados por día de la semana', verbose_name='Requiere configuración por día'),
        ),
        migrations.AddField(
            model_name='tipohorario',
            name='tipo_sistema',
            field=models.CharField(choices=[('FIJO', 'Horario Fijo'), ('TURNO_24H', 'Turno 24x24 horas'), ('ROTATIVO', 'Turno Rotativo'), ('PERSONALIZADO', 'Horario Personalizado por Día')], default='FIJO', max_length=20, verbose_name='Tipo de Sistema'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='qr_code',
            field=models.ImageField(blank=True, storage=checador.storage_backends.MediaStorage(), upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='qr_code',
            field=models.ImageField(blank=True, storage=checador.storage_backends.MediaStorage(), upload_to='qr_visitantes/'),
        ),
        migrations.CreateModel(
            name='SaldoVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_totales', models.DecimalField(decimal_places=2, help_text='Días de vacaciones según antigüedad', max_digits=5, verbose_name='Días totales')),
                ('dias_tomados', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Días tomados')),
                ('fecha_antiguedad', models.DateField(help_text='Fecha de ingreso del empleado para calcular días', verbose_name='Fecha de antigüedad')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_vacaciones', to='attendance.empleado')),
                ('periodo_vacacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.periodovacacional')),
            ],
            options={
                'verbose_name': 'Saldo de Vacaciones',
                'verbose_name_plural': 'Saldos de Vacaciones',
                'ordering': ['-periodo_vacacional__anio'],
                'unique_together': {('empleado', 'periodo_vacacional')},
            },
        ),
        migrations.CreateModel(
            name='SolicitudVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('dias_solicitados', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Días solicitados')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO_JEFE', 'Aprobado por Jefe'), ('APROBADO_GERENCIA', 'Aprobado por Gerencia'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('comentarios_aprobacion', models.TextField(blank=True, verbose_name='Comentarios de aprobación')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacaciones', to='attendance.empleado')),
                ('saldo_vacaciones', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.saldovacaciones')),
            ],
            options={
                'verbose_name': 'Solicitud de Vacaciones',
                'verbose_name_plural': 'Solicitudes de Vacaciones',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='Justificante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_incidente', models.DateField(verbose_name='Fecha del incidente')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('documento_respaldo', models.FileField(blank=True, upload_to='justificantes/', verbose_name='Documento de respaldo')),
                ('fecha_presentacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de presentación')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('comentarios_revision', models.TextField(blank=True, verbose_name='Comentarios de revisión')),
                ('asistencia', models.ForeignKey(blank=True, help_text='Registro de asistencia relacionado (null si es falta completa)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.asistencia')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificantes', to='attendance.empleado')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificantes_revisados', to=settings.AUTH_USER_MODEL)),
                ('tipo_justificante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.tipojustificante')),
            ],
            options={
                'verbose_name': 'Justificante',
                'verbose_name_plural': 'Justificantes',
                'ordering': ['-fecha_presentacion'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('tipo_ausencia', models.CharField(choices=[('DIAS_COMPLETOS', 'Días Completos'), ('HORAS', 'Horas')], default='DIAS_COMPLETOS', max_length=20, verbose_name='Tipo de ausencia')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='Hora de fin')),
                ('total_dias', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Total de días')),
                ('total_horas', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Total de horas')),
                ('con_goce_sueldo', models.BooleanField(default=True, verbose_name='Con goce de sueldo')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO_JEFE', 'Aprobado por Jefe'), ('APROBADO_GERENCIA', 'Aprobado por Gerencia'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('comentarios_aprobacion', models.TextField(blank=True, verbose_name='Comentarios de aprobación')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('archivo_adjunto', models.FileField(blank=True, upload_to='permisos/', verbose_name='Archivo adjunto')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='attendance.empleado')),
                ('tipo_permiso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.tipopermiso')),
            ],
            options={
                'verbose_name': 'Solicitud de Permiso',
                'verbose_name_plural': 'Solicitudes de Permisos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='TurnoRotativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del turno')),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('orden_en_ciclo', models.IntegerField(help_text='1, 2, 3...', verbose_name='Orden en el ciclo')),
                ('dias_consecutivos', models.IntegerField(default=1, help_text='Cuántos días seguidos se trabaja este turno', verbose_name='Días consecutivos')),
                ('tipo_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_rotativos', to='attendance.tipohorario')),
            ],
            options={
                'verbose_name': 'Turno Rotativo',
                'verbose_name_plural': 'Turnos Rotativos',
                'ordering': ['tipo_horario', 'orden_en_ciclo'],
                'unique_together': {('tipo_horario', 'orden_en_ciclo')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionTurnoRotativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('activo', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_turno', to='attendance.empleado')),
                ('turno_rotativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.turnorotativo')),
            ],
            options={
                'verbose_name': 'Asignación de Turno Rotativo',
                'verbose_name_plural': 'Asignaciones de Turnos Rotativos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HorarioDiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la semana')),
                ('es_dia_laboral', models.BooleanField(default=True, verbose_name='Es día laboral')),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('es_medio_dia', models.BooleanField(default=False, verbose_name='Es medio día')),
                ('hora_inicio_comida', models.TimeField(blank=True, null=True, verbose_name='Inicio de comida')),
                ('hora_fin_comida', models.TimeField(blank=True, null=True, verbose_name='Fin de comida')),
                ('tipo_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_dia', to='attendance.tipohorario')),
            ],
            options={
                'verbose_name': 'Horario por Día',
                'verbose_name_plural': 'Horarios por Día',
                'ordering': ['tipo_horario', 'dia_semana'],
                'unique_together': {('tipo_horario', 'dia_semana')},
            },
        ),
    ]
