# Generated by Django 5.2.8 on 2026-02-03 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_periodovacacional_tipojustificante_tipopermiso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='qr_activo',
            field=models.BooleanField(default=True, help_text='El QR se desactiva automáticamente después de la salida', verbose_name='QR Activo'),
        ),
        migrations.CreateModel(
            name='AsignacionTurnoDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('es_descanso', models.BooleanField(default=False, verbose_name='Es día de descanso')),
                ('hora_entrada', models.TimeField(blank=True, null=True, verbose_name='Hora de entrada')),
                ('hora_salida', models.TimeField(blank=True, null=True, verbose_name='Hora de salida')),
                ('cruza_medianoche', models.BooleanField(default=False, help_text='Marca esto si el turno termina al día siguiente (ej: 22:00 a 06:00)', verbose_name='Cruza medianoche')),
                ('notas', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_diarias', to='attendance.empleado')),
                ('turno_rotativo', models.ForeignKey(blank=True, help_text='Selecciona un turno predefinido o deja en blanco para horario personalizado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.turnorotativo', verbose_name='Turno rotativo')),
            ],
            options={
                'verbose_name': 'Asignación de Turno Diaria',
                'verbose_name_plural': 'Asignaciones de Turnos Diarias',
                'ordering': ['fecha', 'empleado'],
                'unique_together': {('empleado', 'fecha')},
            },
        ),
    ]
