# Generated by Django 5.2.8 on 2026-08-24 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_visitante_qr_activo_asignacionturnodiaria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual'), ('TIEMPO_EXTRA', 'Tiempo Extra')], max_length=20, unique=True)),
                ('activo', models.BooleanField(default=True, help_text='Si está desactivado, no se envía ni manual ni automáticamente')),
            ],
            options={
                'verbose_name': 'Configuración de Reporte',
                'verbose_name_plural': 'Configuraciones de Reportes',
            },
        ),
        migrations.CreateModel(
            name='DestinatarioReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='attendance.configuracionreporte')),
            ],
            options={
                'verbose_name': 'Destinatario de Reporte',
                'verbose_name_plural': 'Destinatarios de Reportes',
            },
        ),
        migrations.CreateModel(
            name='EnvioReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual'), ('TIEMPO_EXTRA', 'Tiempo Extra')], max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('periodo_descripcion', models.CharField(max_length=200)),
                ('destinatarios', models.TextField(help_text='Snapshot de a quién se envió, separado por coma')),
                ('origen', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICO', 'Automático')], max_length=20)),
                ('exitoso', models.BooleanField()),
                ('error', models.TextField(blank=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Envío de Reporte',
                'verbose_name_plural': 'Envíos de Reportes',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
